cookie:
  expiry_days: 1
  key: signature_key
  name: nba_auth_cookie

credentials:
  usernames:
    user1:
      email: user1@example.com
      name: name1
      password: 'password1'  
    user2:
      email: user2@example.com
      name: name2
      password: 'password2' 
    user3:
      email: user3@example.com
      name: name3
      password: 'password3'  
